### ISSUE TITLE
Test file path resolution does not work on windows

### ISSUE THREAD

**Issue by qlonik** [nfour/fermenter#37]
https://github.com/nfour/fermenter/blob/64f96f2a8578e4c42809aa3a7d13bc0c9403ee2b/src/lib/parseFeature.ts#L24-L25

These lines are supposed to grab current path up until the beginning of line number and column number specifier. However, resolved windows path start with drive name and colon. So this code erroneously removes entire path to the file on windows.

Maybe in regex, instead of grabbing until first colon, it is possible to grab everything in parenthesis and then strip last elements?

**Comment by nfour** [comment]
Thanks for this. Will look into a cross platform solution, but feel free to fork it and try an alternative regex.

**Comment by nfour** [comment]
Should be in `1.8.0` now.

**Comment by qlonik** [comment]
Yep, it works for me now. Thank you. 😄
